<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="10.2850" tests="3" failures="1">
  <testsuite name="Root Suite" timestamp="2021-03-19T21:46:26" tests="0" file="cypress/integration/RegistrationCard.spec.jsx" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Registration Card" timestamp="2021-03-19T21:46:26" tests="3" time="10.2850" failures="1">
    <testcase name="Registration Card throws validation error if name not entered" time="1.1630" classname="throws validation error if name not entered">
    </testcase>
    <testcase name="Registration Card starts recording if name provided" time="0.0000" classname="starts recording if name provided">
      <failure message="expected 1 to be above 1" type="AssertionError"><![CDATA[AssertionError: expected 1 to be above 1
    at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/integration/RegistrationCard.spec.jsx:164:48)]]></failure>
    </testcase>
    <testcase name="Registration Card test training model" time="9.1220" classname="test training model">
    </testcase>
  </testsuite>
</testsuites>